backend:
  name: github
  repo: eatme-global/internal-documentation
  branch: main
  base_url: https://api.github.com
  auth_endpoint: auth

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "docs"
    label: "Docs"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
